runtime: python38
# api_version: 1
# threadsafe: true

handlers:

- url: /templates
  script: auto

- url: /static
  static_dir: static

- url: /.*
  script: auto
  
# libraries:
#   - name: ssl
#     version: latest